import sqlite3
import os

def setup_database():
    # This creates the file 'analytics.db' in your folder
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    db_path = os.path.join(base_dir, 'analytics.db')
    conn = sqlite3.connect(db_path)
    
    cursor = conn.cursor()

    # Table 1: Stores the actual clusters generated by the AI
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS query_clusters (
            cluster_id INTEGER PRIMARY KEY AUTOINCREMENT,
            cluster_name TEXT NOT NULL,
            cluster_summary TEXT,
            centroid BLOB,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    ''')

    # Table 2: Stores every question asked by students
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS user_queries (
            query_id INTEGER PRIMARY KEY AUTOINCREMENT,
            query_text TEXT NOT NULL,
            answer_text TEXT,
            timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            cluster_id INTEGER,
            FOREIGN KEY (cluster_id) REFERENCES query_clusters (cluster_id)
        )
    ''')

    conn.commit()
    conn.close()
    print("Database 'analytics.db' and tables created successfully!")

if __name__ == "__main__":
    setup_database()